### ISSUE TITLE
Couldn't find the package in Atmosphere ! 

### ISSUE THREAD

**Issue by kaiyes** [jamielob/native-transitions#1]
Hi, 

I was trying to add this package from atmosphere using `meteor add jamielob:native-transitions` but couldn't find it. It gave me this error. Couldn't find it in atmosphere as well. 

![screen shot 2017-01-12 at 15 23 12](https://cloud.githubusercontent.com/assets/5293742/21883854/18c8fb5e-d8db-11e6-9a02-38aa2ec16436.png)

**Comment by jamielob** [comment]
@kaiyes This is just a demo repo.  I switched to using React Native shortly writing this so it didn't make it onto Atmosphere as a package.   If you want to use it you should copy the `packages` directory to your project and use it as shown in this repo.
